Помощь друга
htmlacademy-javascript/2070409-keksobooking-26 pull request #9
Opened 2022-07-12 19:38 UTC by talkingmachine

---
:mortar_board: [Помощь друга](https://up.htmlacademy.ru/javascript/26/user/2070409/tasks/18)

:boom: https://htmlacademy-javascript.github.io/2070409-keksobooking-26/9/

2022-07-13 14:42 UTC, VAnastasia requested changes

2022-07-13 14:42 UTC, VAnastasia commented on js/map/map-start-settings.js
> +export {markerPosition, mainMarker};
нельзя экспортировать let переменные, здесь можно сразу в address.value записать значение, начальные координаты сразу записываются в поле с адресом, а не только при перемещении метки

2022-07-13 14:42 UTC, VAnastasia commented on js/map/map-start-settings.js
> +  iconUrl: '../img/main-pin.svg',
путь до картинок, кажется, надо указать относительно main.js

2022-07-13 17:04 UTC, talkingmachine commented on js/map/map-start-settings.js
> +export {markerPosition, mainMarker};
На счет записывать координаты в поле изначально - если пользователь забудет указать место, он по умолчанию будет сдавать что-то в центре Токио? Зачем тогда required на этом поле?

2022-07-13 17:24 UTC, talkingmachine commented on js/map/map-start-settings.js
> +  iconUrl: '../img/main-pin.svg',
Не очень понял почему относительно main.js, это соглашение? Попробовал изменить путь - возник вопрос
как могут корректно работать все 4 варианта:
'./img/main-pin.svg'
'../img/main-pin.svg'
'../../img/main-pin.svg'
'/img/main-pin.svg'
Прочитал на одном форуме - "Правильный тот путь, по которому изображение по итогу доступно." Как то не помогло

2022-07-14 03:27 UTC, VAnastasia commented on js/map/map-start-settings.js
> +export {markerPosition, mainMarker};
Адрес указывается по координатам главной метки, а она сразу появляется в центре Токио

2022-07-14 03:29 UTC, VAnastasia commented on js/map/map-start-settings.js
> +  iconUrl: '../img/main-pin.svg',
VSCode умеет сам довычислить пути, но вот в опубликованной версии https://htmlacademy-javascript.github.io/2070409-keksobooking-26/9/ пути до картинок неправильные

2022-07-14 11:29 UTC, merged